### ISSUE TITLE
still not compatible with 25.4.0.1

### ISSUE THREAD

**Issue by ads90** [NAXAM/bottomtabbedpage-xamarin-forms#1]
since Xamarin.Android.Support.Design 25.4.0.1 doesn't provide the BottomNavigationMenu
you have to downgrade your Xamarin.Android.Support.Design to 25.3

**Comment by kanvuduc** [comment]
Yep. 25.4.0.1 contains too many bugs anyway. Plz don't upgrade to it.

**Comment by kanvuduc** [comment]
When v25.4.0.2 is released, you probable could update. :).
