### ISSUE TITLE
TabPage sliding indicator animation problem

### ISSUE THREAD

**Issue by o1o1o1o1o2** [NAXAM/bottomtabbedpage-xamarin-forms#2]
when one of children of BottomTabbedPage is xamarin TabbedPage whith two tabs for example, every time I  switch tabs made by BottomTabbedPage and returning to child tab with xamarin TabbedPage - sliding indicator animation when trying to switch tabs in  TabbedPage by clicking on tab name not working first time, and then go to normal behavior unless I again switch tabs made by BottomTabbedPage. 
https://www.youtube.com/watch?v=p-lBmZZfxD0

**Comment by kanvuduc** [comment]
Hi,

I am very clear your issue.

Anyway, it isn't encouraged to use TabbedPage inside TabbedPage like your approach.

Cheers.

**Comment by o1o1o1o1o2** [comment]
Why not? Is there another known issues about that, and if they are, maybe you recommend something for my needs, I'm newbie..

**Comment by kanvuduc** [comment]
Because it isn't the right behavior for designing a mobile app, plz check out Google/Apple guidelines. 

Cheers.

**Comment by o1o1o1o1o2** [comment]
for example in Instagram in the forth bottom tab they have top tab as well...
