### ISSUE TITLE
android.widget.FrameLayout cannot be cast to android.widget.ImageView

### ISSUE THREAD

**Issue by kicc** [NAXAM/bottomtabbedpage-xamarin-forms#3]
The first time opening app => exception : ```android.widget.FrameLayout cannot be cast to android.widget.ImageView```

Bellow my home page xaml :
```
<naxam:BottomTabbedPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
xmlns:naxam="clr-namespace:Naxam.Controls.Forms;assembly=Naxam.Controls.Forms"
xmlns:local="clr-namespace:photocloak.View;assembly=photocloak"
x:Class="photocloak.View.Home">
    <local:Search />
    <local:ListCloak/>
</naxam:BottomTabbedPage>
```

**Comment by fleuverouge** [comment]
Hi @kicc,
Thanks for reaching to us!
Your information is not enough for us to investigate the issue.
Please run our demo project to see if our library works on your side.

**Comment by flamecrow** [comment]
@kicc 
Did you have

`public class MainActivity : global::Xamarin.Forms.Platform.Android.**FormsAppCompatActivity**`

in your MainActivity.cs?

**Comment by tuyen-vuduc** [comment]
@kicc I close this issue due to no response from you.
