### ISSUE TITLE
Migrate to .Net Standard

### ISSUE THREAD

**Issue by danielmeza** [NAXAM/bottomtabbedpage-xamarin-forms#5]
Hi this issue i to track the support for .NET Standard and avoid the warning when include the package in to .NET Standard xamarin forms project. 
warning NU1701: Package 'Naxam.BottomTabbedPage 0.1.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'.

**Comment by tuyen-vuduc** [comment]
Pull-request is always welcome, @danielmeza :).

Cheers.

**Comment by dhindrik** [comment]
Created a pull request for this, https://github.com/NAXAM/bottomtabbedpage-xamarin-forms/pull/7
